export const IranProvinces = [
    {
        id: '01',
        parent_id: null,
        label: "آذربایجان شرقی",
        children: [
            { id: '0101', parent_id: 1, label: "اسکو" },
            { id: '0102', parent_id: 1, label: "اهر" },
            { id: '0103', parent_id: 1, label: "ایلخچی" },
            { id: '0104', parent_id: 1, label: "آبش احمد" },
            { id: '0105', parent_id: 1, label: "آذرشهر" },
            { id: '0106', parent_id: 1, label: "آقكند" },
            { id: '0107', parent_id: 1, label: "باسمنج" },
            { id: '0108', parent_id: 1, label: "بخایش" },
            { id: '0109', parent_id: 1, label: "بستان آباد" },
            { id: '0110', parent_id: 1, label: "بناب" },
            { id: '0111', parent_id: 1, label: "بناب جدید" },
            { id: '0112', parent_id: 1, label: "تبریز" },
            { id: '0113', parent_id: 1, label: "ترك" },
            { id: '0114', parent_id: 1, label: "تركمانچای" },
            { id: '0115', parent_id: 1, label: "تسوج" },
            { id: '0116', parent_id: 1, label: "تیكمه داش" },
            { id: '0117', parent_id: 1, label: "جلفا" },
            { id: '0118', parent_id: 1, label: "خاروانا" },
            { id: '0119', parent_id: 1, label: "خامنه" },
            { id: '0120', parent_id: 1, label: "خراجو" },
            { id: '0121', parent_id: 1, label: "خسروشهر" },
            { id: '0122', parent_id: 1, label: "خمارلو" },
            { id: '0123', parent_id: 1, label: "خواجه" },
            { id: '0124', parent_id: 1, label: "دوزدوزان" },
            { id: '0125', parent_id: 1, label: "زرنق" },
            { id: '0126', parent_id: 1, label: "زنوز" },
            { id: '0127', parent_id: 1, label: "سراب" },
            { id: '0128', parent_id: 1, label: "سردرود" },
            { id: '0129', parent_id: 1, label: "سیس" },
            { id: '0130', parent_id: 1, label: "سیه رود" },
            { id: '0131', parent_id: 1, label: "شبستر" },
            { id: '0132', parent_id: 1, label: "شربیان" },
            { id: '0133', parent_id: 1, label: "شرفخانه" },
            { id: '0134', parent_id: 1, label: "شندآباد" },
            { id: '0135', parent_id: 1, label: "شهرجدیدسهند" },
            { id: '0136', parent_id: 1, label: "صوفیان" },
            { id: '0137', parent_id: 1, label: "عجب شیر" },
            { id: '0138', parent_id: 1, label: "قره آغاج" },
            { id: '0139', parent_id: 1, label: "كشكسرای" },
            { id: '0140', parent_id: 1, label: "كلوانق" },
            { id: '0141', parent_id: 1, label: "كلیبر" },
            { id: '0142', parent_id: 1, label: "كوزه كنان" },
            { id: '0143', parent_id: 1, label: "گوگان" },
            { id: '0144', parent_id: 1, label: "لیلان" },
            { id: '0145', parent_id: 1, label: "مراغه" },
            { id: '0146', parent_id: 1, label: "مرند" },
            { id: '0147', parent_id: 1, label: "ملكان" },
            { id: '0148', parent_id: 1, label: "ممقان" },
            { id: '0149', parent_id: 1, label: "مهربان" },
            { id: '0150', parent_id: 1, label: "میانه" },
            { id: '0151', parent_id: 1, label: "نظركهریزی" },
            { id: '0152', parent_id: 1, label: "وایقان" },
            { id: '0153', parent_id: 1, label: "ورزقان" },
            { id: '0154', parent_id: 1, label: "هادیشهر" },
            { id: '0155', parent_id: 1, label: "هریس" },
            { id: '0156', parent_id: 1, label: "هشترود" },
            { id: '0157', parent_id: 1, label: "هوراند" },
            { id: '0158', parent_id: 1, label: "یامچی" }
        ]
    },
    {
        id: '02',
        parent_id: null,
        label: "آذربایجان غربی",
        children: [
            { id: '0201', parent_id: 2, label: "ارومیه" },
            { id: '0202', parent_id: 2, label: "اشنویه" },
            { id: '0203', parent_id: 2, label: "ایواوغلی" },
            { id: '0204', parent_id: 2, label: "آواجیق" },
            { id: '0205', parent_id: 2, label: "باروق" },
            { id: '0206', parent_id: 2, label: "بازرگان" },
            { id: '0207', parent_id: 2, label: "بوكان" },
            { id: '0208', parent_id: 2, label: "پلدشت" },
            { id: '0209', parent_id: 2, label: "پیرانشهر" },
            { id: '0210', parent_id: 2, label: "تازه شهر" },
            { id: '0211', parent_id: 2, label: "تكاب" },
            { id: '0212', parent_id: 2, label: "چهاربرج" },
            { id: '0213', parent_id: 2, label: "خلیفان" },
            { id: '0214', parent_id: 2, label: "خوی" },
            { id: '0215', parent_id: 2, label: "دیزج دیز" },
            { id: '0216', parent_id: 2, label: "ربط" },
            { id: '0217', parent_id: 2, label: "سردشت" },
            { id: '0218', parent_id: 2, label: "سرو" },
            { id: '0219', parent_id: 2, label: "سلماس" },
            { id: '0220', parent_id: 2, label: "سیلوانه" },
            { id: '0221', parent_id: 2, label: "سیمینه" },
            { id: '0222', parent_id: 2, label: "سیه چشمه" },
            { id: '0223', parent_id: 2, label: "شاهین دژ" },
            { id: '0224', parent_id: 2, label: "شوط" },
            { id: '0225', parent_id: 2, label: "فیرورق" },
            { id: '0226', parent_id: 2, label: "قره ضیاءالدین" },
            { id: '0227', parent_id: 2, label: "قطور" },
            { id: '0228', parent_id: 2, label: "قوشچی" },
            { id: '0229', parent_id: 2, label: "كشاورز" },
            { id: '0230', parent_id: 2, label: "گردكشانه" },
            { id: '0231', parent_id: 2, label: "ماكو" },
            { id: '0232', parent_id: 2, label: "محمدیار" },
            { id: '0233', parent_id: 2, label: "محمودآباد" },
            { id: '0234', parent_id: 2, label: "مهاباد" },
            { id: '0235', parent_id: 2, label: "میاندوآب" },
            { id: '0236', parent_id: 2, label: "میرآباد" },
            { id: '0237', parent_id: 2, label: "نالوس" },
            { id: '0238', parent_id: 2, label: "نقده" },
            { id: '0239', parent_id: 2, label: "نوشین" }
        ]
    },
    {
        id: '03',
        parent_id: null,
        label: "اردبیل",
        children: [
            { id: '0301', parent_id: 3, label: "اردبیل" },
            { id: '0302', parent_id: 3, label: "اصلاندوز" },
            { id: '0303', parent_id: 3, label: "آبی بیگلو" },
            { id: '0304', parent_id: 3, label: "بیله سوار" },
            { id: '0305', parent_id: 3, label: "پارس آباد" },
            { id: '0306', parent_id: 3, label: "تازه كند" },
            { id: '0307', parent_id: 3, label: "تازه كندانگوت" },
            { id: '0308', parent_id: 3, label: "جعفرآباد" },
            { id: '0309', parent_id: 3, label: "خلخال" },
            { id: '0310', parent_id: 3, label: "رضی" },
            { id: '0311', parent_id: 3, label: "سرعین" },
            { id: '0312', parent_id: 3, label: "عنبران" },
            { id: '0313', parent_id: 3, label: "فخرآباد" },
            { id: '0314', parent_id: 3, label: "كلور" },
            { id: '0315', parent_id: 3, label: "كوراییم" },
            { id: '0316', parent_id: 3, label: "گرمی" },
            { id: '0317', parent_id: 3, label: "گیوی" },
            { id: '0318', parent_id: 3, label: "لاهرود" },
            { id: '0319', parent_id: 3, label: "مرادلو" },
            { id: '0320', parent_id: 3, label: "مشگین شهر" },
            { id: '0321', parent_id: 3, label: "نمین" },
            { id: '0322', parent_id: 3, label: "نیر" },
            { id: '0323', parent_id: 3, label: "هشتجین" },
            { id: '0324', parent_id: 3, label: "هیر" }
        ]
    },
    {
        id: '04',
        parent_id: null,
        label: "اصفهان",
        children: [
            { id: '0401', parent_id: 4, label: "ابریشم" },
            { id: '0402', parent_id: 4, label: "ابوزیدآباد" },
            { id: '0403', parent_id: 4, label: "اردستان" },
            { id: '0404', parent_id: 4, label: "اژیه" },
            { id: '0405', parent_id: 4, label: "اصفهان" },
            { id: '0406', parent_id: 4, label: "افوس" },
            { id: '0407', parent_id: 4, label: "انارك" },
            { id: '0408', parent_id: 4, label: "ایمانشهر" },
            { id: '0409', parent_id: 4, label: "آران وبیدگل" },
            { id: '0410', parent_id: 4, label: "بادرود" },
            { id: '0411', parent_id: 4, label: "باغ بهادران" },
            { id: '0412', parent_id: 4, label: "بافران" },
            { id: '0413', parent_id: 4, label: "برزك" },
            { id: '0414', parent_id: 4, label: "برف انبار" },
            { id: '0415', parent_id: 4, label: "بوئین ومیاندشت" },
            { id: '0416', parent_id: 4, label: "بهاران شهر" },
            { id: '0417', parent_id: 4, label: "بهارستان" },
            { id: '0418', parent_id: 4, label: "پیربكران" },
            { id: '0419', parent_id: 4, label: "تودشك" },
            { id: '0420', parent_id: 4, label: "تیران" },
            { id: '0421', parent_id: 4, label: "جندق" },
            { id: '0422', parent_id: 4, label: "جوزدان" },
            { id: '0423', parent_id: 4, label: "جوشقان وكامو" },
            { id: '0424', parent_id: 4, label: "چادگان" },
            { id: '0425', parent_id: 4, label: "چرمهین" },
            { id: '0426', parent_id: 4, label: "چمگردان" },
            { id: '0427', parent_id: 4, label: "حبیب آباد" },
            { id: '0428', parent_id: 4, label: "حسن آباد" },
            { id: '0429', parent_id: 4, label: "حنا" },
            { id: '0430', parent_id: 4, label: "خالدآباد" },
            { id: '0431', parent_id: 4, label: "خمینی شهر" },
            { id: '0432', parent_id: 4, label: "خوانسار" },
            { id: '0433', parent_id: 4, label: "خور" },
            { id: '0434', parent_id: 4, label: "خوراسگان" },
            { id: '0435', parent_id: 4, label: "خورزوق" },
            { id: '0436', parent_id: 4, label: "داران" },
            { id: '0437', parent_id: 4, label: "دامنه" },
            { id: '0438', parent_id: 4, label: "درچه پیاز" },
            { id: '0439', parent_id: 4, label: "دستگرد" },
            { id: '0440', parent_id: 4, label: "دولت آباد" },
            { id: '0441', parent_id: 4, label: "دهاقان" },
            { id: '0442', parent_id: 4, label: "دهق" },
            { id: '0443', parent_id: 4, label: "دیزیچه" },
            { id: '0444', parent_id: 4, label: "رزوه" },
            { id: '0445', parent_id: 4, label: "رضوانشهر" },
            { id: '0446', parent_id: 4, label: "زاینده رود" },
            { id: '0447', parent_id: 4, label: "زرین شهر" },
            { id: '0448', parent_id: 4, label: "زواره" },
            { id: '0449', parent_id: 4, label: "زیباشهر" },
            { id: '0450', parent_id: 4, label: "سده لنجان" },
            { id: '0451', parent_id: 4, label: "سفیدشهر" },
            { id: '0452', parent_id: 4, label: "سگزی" },
            { id: '0453', parent_id: 4, label: "سمیرم" },
            { id: '0454', parent_id: 4, label: "شاپورآباد" },
            { id: '0455', parent_id: 4, label: "شاهین شهر" },
            { id: '0456', parent_id: 4, label: "شهرضا" },
            { id: '0457', parent_id: 4, label: "طالخونچه" },
            { id: '0458', parent_id: 4, label: "عسگران" },
            { id: '0459', parent_id: 4, label: "علویچه" },
            { id: '0460', parent_id: 4, label: "فرخی" },
            { id: '0461', parent_id: 4, label: "فریدونشهر" },
            { id: '0462', parent_id: 4, label: "فلاورجان" },
            { id: '0463', parent_id: 4, label: "فولادشهر" },
            { id: '0464', parent_id: 4, label: "قمصر" },
            { id: '0465', parent_id: 4, label: "قهجاورستان" },
            { id: '0466', parent_id: 4, label: "قهدریجان" },
            { id: '0467', parent_id: 4, label: "كاشان" },
            { id: '0468', parent_id: 4, label: "كركوند" },
            { id: '0469', parent_id: 4, label: "كلیشادوسودرجان" },
            { id: '0470', parent_id: 4, label: "كمشچه" },
            { id: '0471', parent_id: 4, label: "كمه" },
            { id: '0472', parent_id: 4, label: "كوشك" },
            { id: '0473', parent_id: 4, label: "كوهپایه" },
            { id: '0474', parent_id: 4, label: "كهریزسنگ" },
            { id: '0475', parent_id: 4, label: "گرگاب" },
            { id: '0476', parent_id: 4, label: "گزبرخوار" },
            { id: '0477', parent_id: 4, label: "گلپایگان" },
            { id: '0478', parent_id: 4, label: "گلدشت" },
            { id: '0479', parent_id: 4, label: "گلشن" },
            { id: '0480', parent_id: 4, label: "گلشهر" },
            { id: '0481', parent_id: 4, label: "گوگد" },
            { id: '0482', parent_id: 4, label: "لای بید" },
            { id: '0483', parent_id: 4, label: "مباركه" },
            { id: '0484', parent_id: 4, label: "محمدآباد" },
            { id: '0485', parent_id: 4, label: "مشكات" },
            { id: '0486', parent_id: 4, label: "منظریه" },
            { id: '0487', parent_id: 4, label: "مهاباد" },
            { id: '0488', parent_id: 4, label: "میمه" },
            { id: '0489', parent_id: 4, label: "نائین" },
            { id: '0490', parent_id: 4, label: "نجف آباد" },
            { id: '0491', parent_id: 4, label: "نصرآباد" },
            { id: '0492', parent_id: 4, label: "نطنز" },
            { id: '0493', parent_id: 4, label: "نوش آباد" },
            { id: '0494', parent_id: 4, label: "نیاسر" },
            { id: '0495', parent_id: 4, label: "نیك آباد" },
            { id: '0496', parent_id: 4, label: "ورزنه" },
            { id: '0497', parent_id: 4, label: "ورنامخواست" },
            { id: '0498', parent_id: 4, label: "وزوان" },
            { id: '0499', parent_id: 4, label: "ونك" },
            { id: '0500', parent_id: 4, label: "هرند" }
        ]
    },
    {
        id: '05',
        parent_id: null,
        label: "البرز",
        children: [
            { id: '0501', parent_id: 5, label: "اشتهارد" },
            { id: '0502', parent_id: 5, label: "آسارا" },
            { id: '0503', parent_id: 5, label: "تنكمان" },
            { id: '0504', parent_id: 5, label: "چهارباغ" },
            { id: '0505', parent_id: 5, label: "سیف آباد" },
            { id: '0506', parent_id: 5, label: "شهرجدیدهشتگرد" },
            { id: '0507', parent_id: 5, label: "طالقان" },
            { id: '0508', parent_id: 5, label: "كرج" },
            { id: '0509', parent_id: 5, label: "كمال شهر" },
            { id: '0510', parent_id: 5, label: "كوهسار" },
            { id: '0511', parent_id: 5, label: "گرمدره" },
            { id: '0512', parent_id: 5, label: "ماهدشت" },
            { id: '0513', parent_id: 5, label: "محمدشهر" },
            { id: '0514', parent_id: 5, label: "مشكین دشت" },
            { id: '0515', parent_id: 5, label: "نظرآباد" },
            { id: '0516', parent_id: 5, label: "هشتگرد" }
        ]
    },
    {
        id: '06',
        parent_id: null,
        label: "ایلام",
        children: [
            { id: '0601', parent_id: 6, label: "اركواز" },
            { id: '0602', parent_id: 6, label: "ایلام" },
            { id: '0603', parent_id: 6, label: "ایوان" },
            { id: '0604', parent_id: 6, label: "آبدانان" },
            { id: '0605', parent_id: 6, label: "آسمان آباد" },
            { id: '0606', parent_id: 6, label: "بدره" },
            { id: '0607', parent_id: 6, label: "پهله" },
            { id: '0608', parent_id: 6, label: "توحید" },
            { id: '0609', parent_id: 6, label: "چوار" },
            { id: '0610', parent_id: 6, label: "دره شهر" },
            { id: '0611', parent_id: 6, label: "دلگشا" },
            { id: '0612', parent_id: 6, label: "دهلران" },
            { id: '0613', parent_id: 6, label: "زرنه" },
            { id: '0614', parent_id: 6, label: "سراب باغ" },
            { id: '0615', parent_id: 6, label: "سرابله" },
            { id: '0616', parent_id: 6, label: "صالح آباد" },
            { id: '0617', parent_id: 6, label: "لومار" },
            { id: '0618', parent_id: 6, label: "مورموری" },
            { id: '0619', parent_id: 6, label: "موسیان" },
            { id: '0620', parent_id: 6, label: "مهران" },
            { id: '0621', parent_id: 6, label: "میمه" }
        ]
    },
    {
        id: '07',
        parent_id: null,
        label: "بوشهر",
        children: [
            { id: '0701', parent_id: 7, label: "امام حسن" },
            { id: '0702', parent_id: 7, label: "انارستان" },
            { id: '0703', parent_id: 7, label: "اهرم" },
            { id: '0704', parent_id: 7, label: "آبپخش" },
            { id: '0705', parent_id: 7, label: "آبدان" },
            { id: '0706', parent_id: 7, label: "برازجان" },
            { id: '0707', parent_id: 7, label: "بردخون" },
            { id: '0708', parent_id: 7, label: "بردستان" },
            { id: '0709', parent_id: 7, label: "بندردیر" },
            { id: '0710', parent_id: 7, label: "بندردیلم" },
            { id: '0711', parent_id: 7, label: "بندرریگ" },
            { id: '0712', parent_id: 7, label: "بندركنگان" },
            { id: '0713', parent_id: 7, label: "بندرگناوه" },
            { id: '0714', parent_id: 7, label: "بنك" },
            { id: '0715', parent_id: 7, label: "بوشهر" },
            { id: '0716', parent_id: 7, label: "تنگ ارم" },
            { id: '0717', parent_id: 7, label: "جم" },
            { id: '0718', parent_id: 7, label: "چغادك" },
            { id: '0719', parent_id: 7, label: "خارك" },
            { id: '0720', parent_id: 7, label: "خورموج" },
            { id: '0721', parent_id: 7, label: "دالكی" },
            { id: '0722', parent_id: 7, label: "دلوار" },
            { id: '0723', parent_id: 7, label: "ریز" },
            { id: '0724', parent_id: 7, label: "سعدآباد" },
            { id: '0725', parent_id: 7, label: "سیراف" },
            { id: '0726', parent_id: 7, label: "شبانكاره" },
            { id: '0727', parent_id: 7, label: "شنبه" },
            { id: '0728', parent_id: 7, label: "عسلویه" },
            { id: '0729', parent_id: 7, label: "كاكی" },
            { id: '0730', parent_id: 7, label: "كلمه" },
            { id: '0731', parent_id: 7, label: "نخل تقی" },
            { id: '0732', parent_id: 7, label: "وحدتیه" }
        ]
    },
    {
        id: '08',
        parent_id: null,
        label: "تهران",
        children: [
            { id: '0801', parent_id: 8, label: "ارجمند" },
            { id: '0802', parent_id: 8, label: "اسلامشهر" },
            { id: '0803', parent_id: 8, label: "اندیشه" },
            { id: '0804', parent_id: 8, label: "آبسرد" },
            { id: '0805', parent_id: 8, label: "آبعلی" },
            { id: '0806', parent_id: 8, label: "باغستان" },
            { id: '0807', parent_id: 8, label: "باقرشهر" },
            { id: '0808', parent_id: 8, label: "بومهن" },
            { id: '0809', parent_id: 8, label: "پاكدشت" },
            { id: '0810', parent_id: 8, label: "پردیس" },
            { id: '0811', parent_id: 8, label: "پیشوا" },
            { id: '0812', parent_id: 8, label: "تجریش" },
            { id: '0813', parent_id: 8, label: "تهران" },
            { id: '0814', parent_id: 8, label: "جوادآباد" },
            { id: '0815', parent_id: 8, label: "چهاردانگه" },
            { id: '0816', parent_id: 8, label: "حسن آباد" },
            { id: '0817', parent_id: 8, label: "دماوند" },
            { id: '0818', parent_id: 8, label: "رباط كریم" },
            { id: '0819', parent_id: 8, label: "رودهن" },
            { id: '0820', parent_id: 8, label: "ری" },
            { id: '0821', parent_id: 8, label: "شاهدشهر" },
            { id: '0822', parent_id: 8, label: "شریف آباد" },
            { id: '0823', parent_id: 8, label: "شهریار" },
            { id: '0824', parent_id: 8, label: "صالح آباد" },
            { id: '0825', parent_id: 8, label: "صباشهر" },
            { id: '0826', parent_id: 8, label: "صفادشت" },
            { id: '0827', parent_id: 8, label: "فردوسیه" },
            { id: '0828', parent_id: 8, label: "فرون آباد" },
            { id: '0829', parent_id: 8, label: "فشم" },
            { id: '0830', parent_id: 8, label: "فیروزكوه" },
            { id: '0831', parent_id: 8, label: "قدس" },
            { id: '0832', parent_id: 8, label: "قرچك" },
            { id: '0833', parent_id: 8, label: "كهریزك" },
            { id: '0834', parent_id: 8, label: "كیلان" },
            { id: '0835', parent_id: 8, label: "گلستان" },
            { id: '0836', parent_id: 8, label: "لواسان" },
            { id: '0837', parent_id: 8, label: "ملارد" },
            { id: '0838', parent_id: 8, label: "نسیم شهر" },
            { id: '0839', parent_id: 8, label: "نصیرآباد" },
            { id: '0840', parent_id: 8, label: "وحیدیه" },
            { id: '0841', parent_id: 8, label: "ورامین" }
        ]
    },
    {
        id: '09',
        parent_id: null,
        label: "چهارمحال و بختیاری",
        children: [
            { id: '0901', parent_id: 9, label: "اردل" },
            { id: '0902', parent_id: 9, label: "آلونی" },
            { id: '0903', parent_id: 9, label: "باباحیدر" },
            { id: '0904', parent_id: 9, label: "بروجن" },
            { id: '0905', parent_id: 9, label: "بلداجی" },
            { id: '0906', parent_id: 9, label: "بن" },
            { id: '0907', parent_id: 9, label: "جونقان" },
            { id: '0908', parent_id: 9, label: "چلگرد" },
            { id: '0909', parent_id: 9, label: "سامان" },
            { id: '0910', parent_id: 9, label: "سفیددشت" },
            { id: '0911', parent_id: 9, label: "سودجان" },
            { id: '0912', parent_id: 9, label: "سورشجان" },
            { id: '0913', parent_id: 9, label: "شلمزار" },
            { id: '0914', parent_id: 9, label: "شهركرد" },
            { id: '0915', parent_id: 9, label: "طاقانك" },
            { id: '0916', parent_id: 9, label: "فارسان" },
            { id: '0917', parent_id: 9, label: "فرادنبه" },
            { id: '0918', parent_id: 9, label: "فرخ شهر" },
            { id: '0919', parent_id: 9, label: "كیان" },
            { id: '0920', parent_id: 9, label: "گندمان" },
            { id: '0921', parent_id: 9, label: "گهرو" },
            { id: '0922', parent_id: 9, label: "لردگان" },
            { id: '0923', parent_id: 9, label: "مال خلیفه" },
            { id: '0924', parent_id: 9, label: "ناغان" },
            { id: '0925', parent_id: 9, label: "نافچ" },
            { id: '0926', parent_id: 9, label: "نقنه" },
            { id: '0927', parent_id: 9, label: "هفشجان" },
            { id: '0928', parent_id: 9, label: "شیراز" }
        ]
    },
    {
        id: '10',
        parent_id: null,
        label: "خراسان جنوبی",
        children: [
            { id: '1001', parent_id: 10, label: "ارسك" },
            { id: '1002', parent_id: 10, label: "اسدیه" },
            { id: '1003', parent_id: 10, label: "اسفدن" },
            { id: '1004', parent_id: 10, label: "اسلامیه" },
            { id: '1005', parent_id: 10, label: "آرین شهر" },
            { id: '1006', parent_id: 10, label: "آیسك" },
            { id: '1007', parent_id: 10, label: "بشرویه" },
            { id: '1008', parent_id: 10, label: "بیرجند" },
            { id: '1009', parent_id: 10, label: "حاجی آباد" },
            { id: '1010', parent_id: 10, label: "خضری دشت بیاض" },
            { id: '1011', parent_id: 10, label: "خوسف" },
            { id: '1012', parent_id: 10, label: "زهان" },
            { id: '1013', parent_id: 10, label: "سرایان" },
            { id: '1014', parent_id: 10, label: "سربیشه" },
            { id: '1015', parent_id: 10, label: "سه قلعه" },
            { id: '1016', parent_id: 10, label: "شوسف" },
            { id: '1017', parent_id: 10, label: "طبس مسینا" },
            { id: '1018', parent_id: 10, label: "فردوس" },
            { id: '1019', parent_id: 10, label: "قائن" },
            { id: '1020', parent_id: 10, label: "قهستان" },
            { id: '1021', parent_id: 10, label: "گزیك" },
            { id: '1022', parent_id: 10, label: "محمد شهر" },
            { id: '1023', parent_id: 10, label: "مود" },
            { id: '1024', parent_id: 10, label: "نهبندان" },
            { id: '1025', parent_id: 10, label: "نیمبلوك" }
        ]
    },
    {
        id: '11',
        parent_id: null,
        label: "خراسان رضوی",
        children: [
            { id: '1101', parent_id: 11, label: "احمدآبادصولت" },
            { id: '1102', parent_id: 11, label: "انابد" },
            { id: '1103', parent_id: 11, label: "باجگیران" },
            { id: '1104', parent_id: 11, label: "باخرز" },
            { id: '1105', parent_id: 11, label: "بار" },
            { id: '1106', parent_id: 11, label: "بایگ" },
            { id: '1107', parent_id: 11, label: "بجستان" },
            { id: '1108', parent_id: 11, label: "بردسكن" },
            { id: '1109', parent_id: 11, label: "بیدخت" },
            { id: '1110', parent_id: 11, label: "تایباد" },
            { id: '1111', parent_id: 11, label: "تربت جام" },
            { id: '1112', parent_id: 11, label: "تربت حیدریه" },
            { id: '1113', parent_id: 11, label: "جغتای" },
            { id: '1114', parent_id: 11, label: "جنگل" },
            { id: '1115', parent_id: 11, label: "چاپشلو" },
            { id: '1116', parent_id: 11, label: "چكنه" },
            { id: '1117', parent_id: 11, label: "چناران" },
            { id: '1118', parent_id: 11, label: "خرو" },
            { id: '1119', parent_id: 11, label: "خلیل آباد" },
            { id: '1120', parent_id: 11, label: "خواف" },
            { id: '1121', parent_id: 11, label: "داورزن" },
            { id: '1122', parent_id: 11, label: "درگز" },
            { id: '1123', parent_id: 11, label: "درود" },
            { id: '1124', parent_id: 11, label: "دولت آباد" },
            { id: '1125', parent_id: 11, label: "رباط سنگ" },
            { id: '1126', parent_id: 11, label: "رشتخوار" },
            { id: '1127', parent_id: 11, label: "رضویه" },
            { id: '1128', parent_id: 11, label: "روداب" },
            { id: '1129', parent_id: 11, label: "ریوش" },
            { id: '1130', parent_id: 11, label: "سبزوار" },
            { id: '1131', parent_id: 11, label: "سرخس" },
            { id: '1132', parent_id: 11, label: "سفیدسنگ" },
            { id: '1133', parent_id: 11, label: "سلامی" },
            { id: '1134', parent_id: 11, label: "سلطان آباد" },
            { id: '1135', parent_id: 11, label: "سنگان" },
            { id: '1136', parent_id: 11, label: "شادمهر" },
            { id: '1137', parent_id: 11, label: "شاندیز" },
            { id: '1138', parent_id: 11, label: "ششتمد" },
            { id: '1139', parent_id: 11, label: "شهرآباد" },
            { id: '1140', parent_id: 11, label: "شهرزو" },
            { id: '1141', parent_id: 11, label: "صالح آباد" },
            { id: '1142', parent_id: 11, label: "طرقبه" },
            { id: '1143', parent_id: 11, label: "عشق آباد" },
            { id: '1144', parent_id: 11, label: "فرهادگرد" },
            { id: '1145', parent_id: 11, label: "فریمان" },
            { id: '1146', parent_id: 11, label: "فیروزه" },
            { id: '1147', parent_id: 11, label: "فیض آباد" },
            { id: '1148', parent_id: 11, label: "قاسم آباد" },
            { id: '1149', parent_id: 11, label: "قوچان" },
            { id: '1150', parent_id: 11, label: "كاخك" },
            { id: '1151', parent_id: 11, label: "كالپوش" },
            { id: '1152', parent_id: 11, label: "كشمره" },
            { id: '1153', parent_id: 11, label: "گلبهار" },
            { id: '1154', parent_id: 11, label: "لطف آباد" },
            { id: '1155', parent_id: 11, label: "مشهد" },
            { id: '1156', parent_id: 11, label: "مصیری" },
            { id: '1157', parent_id: 11, label: "نقاب" },
            { id: '1158', parent_id: 11, label: "نیشابور" },
            { id: '1159', parent_id: 11, label: "هارونیه" },
            { id: '1160', parent_id: 11, label: "یونسی" }
        ]
    },
    {
        id: '12',
        parent_id: null,
        label: "خراسان شمالی",
        children: [
            { id: '1201', parent_id: 12, label: "اسفراین" },
            { id: '1202', parent_id: 12, label: "بجنورد" },
            { id: '1203', parent_id: 12, label: "جاجرم" },
            { id: '1204', parent_id: 12, label: "شیروان" },
            { id: '1205', parent_id: 12, label: "فاروج" },
            { id: '1206', parent_id: 12, label: "گرمه" }
        ]
    },
    {
        id: '13',
        parent_id: null,
        label: "خوزستان",
        children: [
            { id: '1301', parent_id: 13, label: "آبادان" },
            { id: '1302', parent_id: 13, label: "آغاجاری" },
            { id: '1303', parent_id: 13, label: "ایذه" },
            { id: '1304', parent_id: 13, label: "اندیمشک" },
            { id: '1305', parent_id: 13, label: "اهواز" },
            { id: '1306', parent_id: 13, label: "ایوانك" },
            { id: '1307', parent_id: 13, label: "باغ ملک" },
            { id: '1308', parent_id: 13, label: "بندر امام خمینی" },
            { id: '1309', parent_id: 13, label: "بندر ماهشهر" },
            { id: '1310', parent_id: 13, label: "بهبهان" },
            { id: '1311', parent_id: 13, label: "خرمشهر" },
            { id: '1312', parent_id: 13, label: "دزفول" },
            { id: '1313', parent_id: 13, label: "دشت آزادگان" },
            { id: '1314', parent_id: 13, label: "رامشیر" },
            { id: '1315', parent_id: 13, label: "رامهرمز" },
            { id: '1316', parent_id: 13, label: "سردشت" },
            { id: '1317', parent_id: 13, label: "سوسنگرد" },
            { id: '1318', parent_id: 13, label: "شادگان" },
            { id: '1319', parent_id: 13, label: "شهرستان" },
            { id: '1320', parent_id: 13, label: "شوشتر" },
            { id: '1321', parent_id: 13, label: "صالح شهر" },
            { id: '1322', parent_id: 13, label: "صفی آباد" },
            { id: '1323', parent_id: 13, label: "قلعه خواجه" },
            { id: '1324', parent_id: 13, label: "گتوند" },
            { id: '1325', parent_id: 13, label: "لالی" },
            { id: '1326', parent_id: 13, label: "مسجد سلیمان" },
            { id: '1327', parent_id: 13, label: "مهر" },
            { id: '1328', parent_id: 13, label: "هندیجان" },
            { id: '1329', parent_id: 13, label: "هفتگل" },
            { id: '1330', parent_id: 13, label: "هویزه" },
            { id: '1331', parent_id: 13, label: "حمیدیه" }
        ]
    },
    {
        id: '14',
        parent_id: null,
        label: "زنجان",
        children: [
            { id: '1401', parent_id: 14, label: "ابهر" },
            { id: '1402', parent_id: 14, label: "ایجرود" },
            { id: '1403', parent_id: 14, label: "خدابنده" },
            { id: '1404', parent_id: 14, label: "خرمدره" },
            { id: '1405', parent_id: 14, label: "زرین آباد" },
            { id: '1406', parent_id: 14, label: "زنجان" },
            { id: '1407', parent_id: 14, label: "سلطانیه" },
            { id: '1408', parent_id: 14, label: "قیدار" },
            { id: '1409', parent_id: 14, label: "ماه نشان" }
        ]
    },
    {
        id: '15',
        parent_id: null,
        label: "سمنان",
        children: [
            { id: '1501', parent_id: 15, label: "آرادان" },
            { id: '1502', parent_id: 15, label: "بسطام" },
            { id: '1503', parent_id: 15, label: "دامغان" },
            { id: '1504', parent_id: 15, label: "سرخه" },
            { id: '1505', parent_id: 15, label: "سمنان" },
            { id: '1506', parent_id: 15, label: "شاهرود" },
            { id: '1507', parent_id: 15, label: "گرمسار" },
            { id: '1508', parent_id: 15, label: "میامی" }
        ]
    },
    {
        id: '16',
        parent_id: null,
        label: "سیستان و بلوچستان",
        children: [
            { id: '1601', parent_id: 16, label: "ایرانشهر" },
            { id: '1602', parent_id: 16, label: "چابهار" },
            { id: '1603', parent_id: 16, label: "خاش" },
            { id: '1604', parent_id: 16, label: "زابل" },
            { id: '1605', parent_id: 16, label: "زاهدان" },
            { id: '1606', parent_id: 16, label: "سراوان" },
            { id: '1607', parent_id: 16, label: "سرباز" },
            { id: '1608', parent_id: 16, label: "سیب و سوران" },
            { id: '1609', parent_id: 16, label: "كنارك" },
            { id: '1610', parent_id: 16, label: "مهرستان" },
            { id: '1611', parent_id: 16, label: "نیك شهر" },
            { id: '1612', parent_id: 16, label: "هیرمند" }
        ]
    },
    {
        id: '17',
        parent_id: null,
        label: "فارس",
        children: [
            { id: '1701', parent_id: 17, label: "آباده" },
            { id: '1702', parent_id: 17, label: "ارسنجان" },
            { id: '1703', parent_id: 17, label: "استهبان" },
            { id: '1704', parent_id: 17, label: "اقلید" },
            { id: '1705', parent_id: 17, label: "بوانات" },
            { id: '1706', parent_id: 17, label: "بهرم" },
            { id: '1707', parent_id: 17, label: "پاسارگاد" },
            { id: '1708', parent_id: 17, label: "جهرم" },
            { id: '1709', parent_id: 17, label: "خان زنیان" },
            { id: '1710', parent_id: 17, label: "خنج" },
            { id: '1711', parent_id: 17, label: "داراب" },
            { id: '1712', parent_id: 17, label: "زرین دشت" },
            { id: '1713', parent_id: 17, label: "سپیدان" },
            { id: '1714', parent_id: 17, label: "سرچهان" },
            { id: '1715', parent_id: 17, label: "شیراز" },
            { id: '1716', parent_id: 17, label: "فراشبند" },
            { id: '1717', parent_id: 17, label: "فیروزآباد" },
            { id: '1718', parent_id: 17, label: "قیر و كارزین" },
            { id: '1719', parent_id: 17, label: "كازرون" },
            { id: '1720', parent_id: 17, label: "لامرد" },
            { id: '1721', parent_id: 17, label: "مرودشت" },
            { id: '1722', parent_id: 17, label: "مهر" },
            { id: '1723', parent_id: 17, label: "نورآباد" },
            { id: '1724', parent_id: 17, label: "نی ریز" }
        ]
    },
    {
        id: '18',
        parent_id: null,
        label: "قزوین",
        children: [
            { id: '1801', parent_id: 18, label: "آبیك" },
            { id: '1802', parent_id: 18, label: "البرز" },
            { id: '1803', parent_id: 18, label: "بوئین زهرا" },
            { id: '1804', parent_id: 18, label: "تاكستان" },
            { id: '1805', parent_id: 18, label: "قزوین" },
            { id: '1806', parent_id: 18, label: "محمودیه نزدیک" }
        ]
    },
    {
        id: '19',
        parent_id: null,
        label: "قم",
        children: [
            { id: '1901', parent_id: 19, label: "قم" },
            { id: '1902', parent_id: 19, label: "جعفریه" },
            { id: '1903', parent_id: 19, label: "دستجرد" },
            { id: '1904', parent_id: 19, label: "قنوات" },
            { id: '1905', parent_id: 19, label: "كهك" }
        ]
    },
    {
        id: '20',
        parent_id: null,
        label: "کردستان",
        children: [
            { id: '2001', parent_id: 20, label: "بانه" },
            { id: '2002', parent_id: 20, label: "بیجار" },
            { id: '2003', parent_id: 20, label: "دیواندره" },
            { id: '2004', parent_id: 20, label: "سردشت" },
            { id: '2005', parent_id: 20, label: "سقز" },
            { id: '2006', parent_id: 20, label: "سنندج" },
            { id: '2007', parent_id: 20, label: "قروه" },
            { id: '2008', parent_id: 20, label: "كامیاران" },
            { id: '2009', parent_id: 20, label: "مریوان" }
        ]
    },
    {
        id: '21',
        parent_id: null,
        label: "کرمان",
        children: [
            { id: '2101', parent_id: 21, label: "بافت" },
            { id: '2102', parent_id: 21, label: "بردسیر" },
            { id: '2103', parent_id: 21, label: "بم" },
            { id: '2104', parent_id: 21, label: "جیرفت" },
            { id: '2105', parent_id: 21, label: "رابر" },
            { id: '2106', parent_id: 21, label: "راور" },
            { id: '2107', parent_id: 21, label: "رفسنجان" },
            { id: '2108', parent_id: 21, label: "زرند" },
            { id: '2109', parent_id: 21, label: "سیرجان" },
            { id: '2110', parent_id: 21, label: "شهربابك" },
            { id: '2111', parent_id: 21, label: "فهرج" },
            { id: '2112', parent_id: 21, label: "كرمان" },
            { id: '2113', parent_id: 21, label: "كوهبنان" },
            { id: '2114', parent_id: 21, label: "كهنوج" },
            { id: '2115', parent_id: 21, label: "منوجان" },
            { id: '2116', parent_id: 21, label: "نرماشیر" },
            { id: '2117', parent_id: 21, label: "یافت" }
        ]
    },
    {
        id: '22',
        parent_id: null,
        label: "کرمانشاه",
        children: [
            { id: '2201', parent_id: 22, label: "اسلام آباد غرب" },
            { id: '2202', parent_id: 22, label: "پاوه" },
            { id: '2203', parent_id: 22, label: "ثلاث باباجانی" },
            { id: '2204', parent_id: 22, label: "جوانرود" },
            { id: '2205', parent_id: 22, label: "دالاهو" },
            { id: '2206', parent_id: 22, label: "روانسر" },
            { id: '2207', parent_id: 22, label: "سرپل ذهاب" },
            { id: '2208', parent_id: 22, label: "سرمست" },
            { id: '2209', parent_id: 22, label: "صحنه" },
            { id: '2210', parent_id: 22, label: "قصر شیرین" },
            { id: '2211', parent_id: 22, label: "كرمانشاه" },
            { id: '2212', parent_id: 22, label: "كنگاور" },
            { id: '2213', parent_id: 22, label: "گیلان غرب" },
            { id: '2214', parent_id: 22, label: "هرسین" }
        ]
    },
    {
        id: '23',
        parent_id: null,
        label: "کهگیلویه و بویراحمد",
        children: [
            { id: '2301', parent_id: 23, label: "باشت" },
            { id: '2302', parent_id: 23, label: "پاتاوه" },
            { id: '2303', parent_id: 23, label: "چرام" },
            { id: '2304', parent_id: 23, label: "دنا" },
            { id: '2305', parent_id: 23, label: "دوگنبدان" },
            { id: '2306', parent_id: 23, label: "سوق" },
            { id: '2307', parent_id: 23, label: "سی سخت" },
            { id: '2308', parent_id: 23, label: "گچساران" },
            { id: '2309', parent_id: 23, label: "لیكك" },
            { id: '2310', parent_id: 23, label: "مارگون" },
            { id: '2311', parent_id: 23, label: "یاسوج" }
        ]
    },
    {
        id: '24',
        parent_id: null,
        label: "گلستان",
        children: [
            { id: '2401', parent_id: 24, label: "آزادشهر" },
            { id: '2402', parent_id: 24, label: "آق قلا" },
            { id: '2403', parent_id: 24, label: "بندر تركمن" },
            { id: '2404', parent_id: 24, label: "بندر گز" },
            { id: '2405', parent_id: 24, label: "رامیان" },
            { id: '2406', parent_id: 24, label: "علی آباد كتول" },
            { id: '2407', parent_id: 24, label: "كردكوی" },
            { id: '2408', parent_id: 24, label: "گرگان" },
            { id: '2409', parent_id: 24, label: "گنبد كاووس" },
            { id: '2410', parent_id: 24, label: "مینودشت" },
            { id: '2411', parent_id: 24, label: "نقده خانه" }
        ]
    },
    {
        id: '25',
        parent_id: null,
        label: "گیلان",
        children: [
            { id: '2501', parent_id: 25, label: "آستارا" },
            { id: '2502', parent_id: 25, label: "استانه اشرفیه" },
            { id: '2503', parent_id: 25, label: "املش" },
            { id: '2504', parent_id: 25, label: "بندر انزلی" },
            { id: '2505', parent_id: 25, label: "پره سر" },
            { id: '2506', parent_id: 25, label: "رشت" },
            { id: '2507', parent_id: 25, label: "رضوانشهر" },
            { id: '2508', parent_id: 25, label: "رودبار" },
            { id: '2509', parent_id: 25, label: "رودسر" },
            { id: '2510', parent_id: 25, label: "سیاهكل" },
            { id: '2511', parent_id: 25, label: "شفت" },
            { id: '2512', parent_id: 25, label: "صومعه سرا" },
            { id: '2513', parent_id: 25, label: "طالش" },
            { id: '2514', parent_id: 25, label: "فومن" },
            { id: '2515', parent_id: 25, label: "لاهیجان" },
            { id: '2516', parent_id: 25, label: "لنگرود" },
            { id: '2517', parent_id: 25, label: "ماسال" },
            { id: '2518', parent_id: 25, label: "مرداب" }
        ]
    },
    {
        id: '26',
        parent_id: null,
        label: "لرستان",
        children: [
            { id: '2601', parent_id: 26, label: "الشتر" },
            { id: '2602', parent_id: 26, label: "ازنا" },
            { id: '2603', parent_id: 26, label: "بروجرد" },
            { id: '2604', parent_id: 26, label: "پلدختر" },
            { id: '2605', parent_id: 26, label: "خرم آباد" },
            { id: '2606', parent_id: 26, label: "دورود" },
            { id: '2607', parent_id: 26, label: "دلفان" },
            { id: '2608', parent_id: 26, label: "سپیددشت" },
            { id: '2609', parent_id: 26, label: "شوشتر" },
            { id: '2610', parent_id: 26, label: "كوهدشت" },
            { id: '2611', parent_id: 26, label: "نورآباد" },
            { id: '2612', parent_id: 26, label: "الیگودرز" }
        ]
    },
    {
        id: '27',
        parent_id: null,
        label: "مازندران",
        children: [
            { id: '2701', parent_id: 27, label: "آمل" },
            { id: '2702', parent_id: 27, label: "بابلسر" },
            { id: '2703', parent_id: 27, label: "بهشهر" },
            { id: '2704', parent_id: 27, label: "تنكابن" },
            { id: '2705', parent_id: 27, label: "جویبار" },
            { id: '2706', parent_id: 27, label: "چالوس" },
            { id: '2707', parent_id: 27, label: "رامسر" },
            { id: '2708', parent_id: 27, label: "ساری" },
            { id: '2709', parent_id: 27, label: "سوادكوه" },
            { id: '2710', parent_id: 27, label: "قائم شهر" },
            { id: '2711', parent_id: 27, label: "كلاردشت" },
            { id: '2712', parent_id: 27, label: "محمودآباد" },
            { id: '2713', parent_id: 27, label: "نكا" },
            { id: '2714', parent_id: 27, label: "نور" },
            { id: '2715', parent_id: 27, label: "نوشهر" }
        ]
    },
    {
        id: '28',
        parent_id: null,
        label: "مرکزی",
        children: [
            { id: '2801', parent_id: 28, label: "آشتیان" },
            { id: '2802', parent_id: 28, label: "اراك" },
            { id: '2803', parent_id: 28, label: "تفرش" },
            { id: '2804', parent_id: 28, label: "خمین" },
            { id: '2805', parent_id: 28, label: "دلیجان" },
            { id: '2806', parent_id: 28, label: "زرندیه" },
            { id: '2807', parent_id: 28, label: "ساوه" },
            { id: '2808', parent_id: 28, label: "شازند" },
            { id: '2809', parent_id: 28, label: "كمیجان" },
            { id: '2810', parent_id: 28, label: "محلات" },
            { id: '2811', parent_id: 28, label: "خنداب" }
        ]
    },
    {
        id: '29',
        parent_id: null,
        label: "هرمزگان",
        children: [
            { id: '2901', parent_id: 29, label: "ابوموسی" },
            { id: '2902', parent_id: 29, label: "بستك" },
            { id: '2903', parent_id: 29, label: "بندر عباس" },
            { id: '2904', parent_id: 29, label: "بندر لنگه" },
            { id: '2905', parent_id: 29, label: "پارسیان" },
            { id: '2906', parent_id: 29, label: "جاسك" },
            { id: '2907', parent_id: 29, label: "حاجی آباد" },
            { id: '2908', parent_id: 29, label: "خمیر" },
            { id: '2909', parent_id: 29, label: "رودان" },
            { id: '2910', parent_id: 29, label: "سیریك" },
            { id: '2911', parent_id: 29, label: "قشم" },
            { id: '2912', parent_id: 29, label: "گاوبندی" },
            { id: '2913', parent_id: 29, label: "میناب" },
            { id: '2914', parent_id: 29, label: "هشتبندی" }
        ]
    },
    {
        id: '30',
        parent_id: null,
        label: "همدان",
        children: [
            { id: '3001', parent_id: 30, label: "اسدآباد" },
            { id: '3002', parent_id: 30, label: "بهار" },
            { id: '3003', parent_id: 30, label: "تویسركان" },
            { id: '3004', parent_id: 30, label: "رزن" },
            { id: '3005', parent_id: 30, label: "فامنین" },
            { id: '3006', parent_id: 30, label: "كبودرآهنگ" },
            { id: '3007', parent_id: 30, label: "ملایر" },
            { id: '3008', parent_id: 30, label: "نهاوند" },
            { id: '3009', parent_id: 30, label: "همدان" }
        ]
    },
    {
        id: '31',
        parent_id: null,
        label: "یزد",
        children: [
            { id: '3101', parent_id: 31, label: "ابركوه" },
            { id: '3102', parent_id: 31, label: "اردكان" },
            { id: '3103', parent_id: 31, label: "بافق" },
            { id: '3104', parent_id: 31, label: "تفت" },
            { id: '3105', parent_id: 31, label: "خاتم" },
            { id: '3106', parent_id: 31, label: "صدوق" },
            { id: '3107', parent_id: 31, label: "طبس" },
            { id: '3108', parent_id: 31, label: "میبد" },
            { id: '3109', parent_id: 31, label: "یزد" },
            { id: '3110', parent_id: 31, label: "اشكذر" },
            { id: '3111', parent_id: 31, label: "هرات" }
        ]
    }
];