export const WalletLevel = [
    {
        id: 1,
        title: "ریال - عادی",
        limitList: [
            {
                id: 1,
                function: "CI",
                functionLabel: "شارژ",
                period: "Daily",
                periodLabel: "روزانه",
                value: 10000000,
            },
            {
                id: 2,
                function: "CI",
                functionLabel: "شارژ",
                period: "Trnx",
                periodLabel: "به ازای هر درخواست",
                value: 5000000,
            },
            {
                id: 3,
                function: "CO",
                functionLabel: "برداشت",
                period: "Forb",
                periodLabel: "غیر مجاز",
            },
            {
                id: 4,
                function: "T",
                functionLabel: "انتقال",
                period: "Forb",
                periodLabel: "غیر مجاز",
            },
        ],
    },
    {
        id: 8,
        title: "طلا داخلی - تست - عادی",
        limitList: [
            {
                id: 8,
                function: "CI",
                functionLabel: "خرید طلا",
                period: "Forb",
                periodLabel: "غیر مجاز",
                value: 5000000,
            },
            {
                id: 9,
                function: "CO",
                functionLabel: "فروش طلا",
                period: "Forb",
                periodLabel: "غیر مجاز",
            },
            {
                id: 10,
                function: "T",
                functionLabel: "انتقال طلا",
                period: "Forb",
                periodLabel: "غیر مجاز",
            },
        ],
    },
    {
        id: 9,
        title: "طلا - تست - عادی",
        limitList: [
            {
                id: 5,
                function: "CI",
                functionLabel: "خرید طلا",
                period: "Trnx",
                periodLabel: "به ازای هر خرید",
                value: 1000,
            },
            {
                id: 6,
                function: "CO",
                functionLabel: "فروش طلا",
                period: "Trnx",
                periodLabel: "به ازای هر فروش",
                value: 1000,
            },
            {
                id: 7,
                function: "T",
                functionLabel: "انتقال طلا",
                period: "Trnx",
                periodLabel: "به ازای هر انتقال",
                value: 1000,
            },
        ],
    },
    {
        id: 10,
        title: "طلا - تست - خوب",
        limitList: [
            {
                id: 11,
                function: "CI",
                functionLabel: "خرید طلا",
                period: "Trnx",
                periodLabel: "به ازای هر خرید",
                value: 100000,
            },
            {
                id: 12,
                function: "CIo",
                functionLabel: "درخواست واریز",
                period: "Trnx",
                periodLabel: "به ازای هر درخواست واریز",
                value: 100000,
            },
            {
                id: 13,
                function: "CO",
                functionLabel: "فروش طلا",
                period: "Trnx",
                periodLabel: "به ازای هر درخواست برداشت",
                value: 100000,
            },
            {
                id: 14,
                function: "T",
                functionLabel: "انتقال طلا",
                period: "Trnx",
                periodLabel: "به ازای هر درخواست انتقال",
                value: 100000,
            },
        ],
    },
];
